---
- name: "Initialize first control plane"
  ansible.builtin.shell: 
    kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_output

- name: Update bash-completion
  ansible.builtin.shell:
    kubectl completion bash > /usr/share/bash-completion/completions/kubectl
- name: Prepearing to use
  ansible.builtin.shell:
    mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
  become: false
- name: Install CNI
  become: false
  ansible.builtin.shell:
    kubectl create -f {{ cni_url }}
- name: Disable control-node taint
  become: false
  ansible.builtin.shell:
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-
- name: Final
  ansible.builtin.debug:
    msg: 
    - Done. If you want to add workers please use deploy-k8s-worker with theese variables
    - token':' {{ kubeadm_output.stdout_lines[-2:-1] | regex_replace('kubeadm join .* --token') | regex_replace('\\') }}
    - discovery_token':' {{ kubeadm_output.stdout_lines[-1:] | regex_replace('\\t--discovery-token-ca-cert-hash')}}
    - control_plane':' {{ kubeadm_output.stdout_lines[-2:-1] | regex_search('((\d{,3}\.?){4}:\d{1,5})') | regex_replace('\\') }}