---
# tasks file for deploy_k8s
- ansible.builtin.include_tasks:
    package_manager.yaml
- ansible.builtin.include_tasks:
    preparation.yaml
- ansible.builtin.include_tasks:
    configure-k8s-master.yaml
  when: {{ node_role }} == "control_node"
- ansible.builtin.include_tasks:
        configure-k8s-worker.yaml
  when: {{ node_role }} == "worker"